name: builder

on:
  push:
    branches:
      - 'main'
      - 'release-*'

  pull_request:
    branches:
      - 'main'
      - 'release-*'
  
defaults:
  run:
    shell: bash
jobs:

  prepare_ci_run:
    name: Build Website
    # Prepare CI Run looks at what has been changed in this commit/PR/... and determines which artifacts should be
    # built afterwards (in other jobs that depend on this one).
    runs-on: ubuntu-22.04
    
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0 # need to checkout "all commits" for certain features to work (e.g., get all changed files)

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: '21'

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: '^1.17'

      - name: Build CodeLabs
        run: |
          go install github.com/googlecodelabs/tools/claat@latest
          for i in $(ls *.md); do claat export $i; done
        working-directory: ./site/codelabs

      - name: Build Site
        run: |
          npm install
          gulp dist 
          rm -f ./dist/codelabs
          cp -r ./codelabs ./dist/
        working-directory: ./site
